### ISSUE TITLE
Push flow should not require me to store datapackage.json remotely

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#96]
* Why do I need to have a repo with metadata on GitHub? This seems redundant...
  * answer: it is not necessarily Github, but we need to have dp.json somewhere remotely as planner requires it
    * but this shouldn't be this way - as a regular user, I just want to create `flow.yaml` locally and do `data push-flow`

As a Publisher, I want to create `flow.yaml` file for my remote data and publish it instantly to DataHub so I don't need to do any extra work such as storing it in a remote place.

## Acceptance criteria

* [ ] I can create `flow.yaml` and include all necessary information there (eg, descriptor, processing steps) and then I can publish it to DataHub without any other files/steps

**Comment by AcckiyGerman** [comment]
Irakly had implemented https://github.com/datahq/datahub-client/issues/10 so now `.datahub/dp.json` grabbed locally, if exists.
BUT we still (at 24 jan) should put meta-data, such as (title, description, readme) in the `.datahub/dp.json`, not in `flow.yaml` otherwise it will not appear on the datahub page after processing.

**Comment by zelima** [comment]
FIXED
@AcckiyGerman please open a separate issue for that. That's not related (and not sure why that is an issue)
